language: node_js

node_js:
  - "8.9.4"

sudo: true

env:
  - CXX=g++-4.8
  - NODE_API_DB_NAME_TEST=training
  - NODE_ENV=testing
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE training;" -U postgres

script:
  - cd training-node
  - npm install
  - npm run migrations
  - npm test
